#if !defined ( INCLUDED_VIEWPORT_H )
#define INCLUDED_VIEWPORT_H

enum ViewportId {
	VP_NONE,
#if defined(GL_UNSHARED_CONTEXT)
	VP_CAMWINDOW,
	VP_TEXWINDOW,
	VP_XYWINDOW,
#else // !GL_UNSHARED_CONTEXT
	VP_SHARED,
	VP_CAMWINDOW = VP_SHARED,
	VP_TEXWINDOW = VP_SHARED,
	VP_XYWINDOW = VP_SHARED,
#endif // !GL_UNSHARED_CONTEXT
	VP_MAX
};

#endif // INCLUDED_VIEWPORT_H
