.DEFAULT_GOAL := all

all:
	xdg-mime install x-map.xml
	xdg-icon-resource install --size 512 --novendor application-x-map.png
	xdg-icon-resource install --size 512 --novendor netradiant.png
	xdg-desktop-menu install --novendor netradiant.desktop
